import Head from "next/head";
import Image from "next/image";
import { Button } from '@instructure/ui-buttons'
import { View } from '@instructure/ui-view'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <View display="block">
          <Button color="primary" margin="small">
            Primary
          </Button>
          <Button color="secondary" margin="small">
            Secondary
          </Button>
          <Button color="success" margin="small">
            Success
          </Button>
          <Button color="danger" margin="small">
            Danger
          </Button>
          <Button  margin="small">
            Danger
          </Button>
          <Button color="primary-inverse" margin="small">
            Primary Inverse
          </Button>
        </View>
        <div>hello wordl</div>
      </main>
    </div>
  );
}
